### ISSUE TITLE
Raise exception on timeout

### ISSUE THREAD

**Issue by gmyuval** [ParallelSSH/parallel-ssh#101]
**Current behaviour:**

When joining a command with timeout and timeout was reached, the call returns without any exception making it extremely hard to know whether the command finished successfully or has timedout.

**Desired behaviour:**
`pssh.pssh2_client.ParallelSSHClient.join()`
should either raise an exception when timeout was reached or use another method to notify the caller that the command did not complete successfully

**Comment by pkittenis** [comment]
Hi there,

Thank you for the interest.

Yes, this sounds like a good idea, had been thinking about the same.

For now, can do the following to check if commands have finished after calling `join` with a timeout:

```
client.join(output, timeout=5)
while not client.finished(output):
    <do something else>
    client.join(output, timeout=5)
```

**Comment by pkittenis** [comment]
`1.4.0` now raises `pssh.exceptions.Timeout` when timeout is set and reached with commands still running.

**Comment by gmyuval** [comment]
@pkittenis great. Thanks.
