### ISSUE TITLE
run_command on pssh.pssh2_client - new "timeout" option does not seem work 

### ISSUE THREAD

**Issue by parisnps** [ParallelSSH/parallel-ssh#102]
### First thanks for bringing timeout option to run_command on native ssh with V1.3.2.  However, i dont seem to make it work correctly ? I have hit 2 bugs, first of which is reproduced below ... The second one is for truncated output of large XML file [ I will file a separate bug ]

How to reproduce:
------------------------------------------------

```
from pprint import pprint
from pssh.pssh2_client import ParallelSSHClient
from pssh.utils import load_private_key
from collections import defaultdict
import os, sys
import time
hosts=['x','y','z']
client = ParallelSSHClient(hosts)
output = client.run_command('%s', host_args=('sleep 55;echo "running pre-timeout";sleep 55;echo "running post timeout"','sleep 55;echo "running pre-timeout";sleep 55;echo "running post timeout"','sleep 55;echo "running pre-timeout";sleep 55;echo "running post timeout"'), timeout=60)

for host,host_output in output.items():
        print host
        for line in host_output.stdout:
                print line
        for line in host_output.stderr:
                print 'error',line
```
--------------------------------------------------------- 

Output: The timeout seems to work on only 1 host ? What am I missing ?
---------------------------------------------------------
x
running pre-timeout
y
running pre-timeout
_**running post timeout**_
z
running pre-timeout
_**running post timeout**_

**Comment by pkittenis** [comment]
Hi there,

Thanks for the interest.

What was expected behaviour in this case?

As far as can be seen from the above, behaviour is as expected. The timeout setting on `run_command` is for per host reading of stdout/stderr.

For the first host, it times out after pre-timeout and before post-timeout (55sec of one sleep + 5 of other out of 60sec timeout). For the second and third hosts by the time their stdout is read, 60 (first host timeout) + at most 60 seconds (second and third host timeouts each) have passed which is over the 55second wait before post-timeout as well as over the overall 55+55 second duration.

Therefore no timeout for second or third host. If this is not what was expected, can you make a smaller test case to demonstrate? As a side note, since commands are the same, `host_args` is not needed.

**Comment by parisnps** [comment]
Hi there,

Thanks for the response. Before I create a testcase, I have something basic to clear out first, thanks for your patience on this. Taking a step back to explain the situation I am trying to solve.

- I am trying to run same/similar command on three host x,y,z concurrently  [ in reality it is much larger ]
- Sometimes, in few hosts, the command hangs which disrupts the whole script execution and it used to hang. With the new timeout option on run_command, I was hoping to kill the session on all host if it has not completed already by a given  timeout value. That would be very neat solution.
- In above example,  I wanted a timeout of 60 seconds on all the 3 hosts when it starts to run the command parallely. 

When I put the timeout option in the run_command 
 
`output = client.run_command('%s', host_args=('sleep 55;echo "running pre-timeout";sleep 55;echo "running post timeout"','sleep 55;echo "running pre-timeout";sleep 55;echo "running post timeout"','sleep 55;echo "running pre-timeout";sleep 55;echo "running post timeout"'), **timeout=60**)
`
Shouldn't this timeout be for stdout/err of all the parallel session  on 3 hosts which are out there rather than for x alone ? How can I enforce a timeout of 60 seconds on all 3 sessions concurrently. I would expect all of them to fail before ending post timeout. 

Thanks

**Comment by pkittenis** [comment]
`client.join(output, timeout=60)`

`timeout` on `run_command` is for the individual host stdout/stderr channels (see [docs](http://parallel-ssh.readthedocs.io/en/latest/pssh2_client.html#pssh.pssh2_client.ParallelSSHClient.run_command)).

`join` timeout is a per-host wait time which, if exceeded, the `join` call will raise `Timeout` exception along with which host the timeout occurred on. If the script should not wait for more than N seconds in total for all hosts then join timeout can be set to `N/len(client.hosts)`.

This of course assuming the commands are hanging on execution and not connection/authentication (ie, `run_command` has returned). Connection/authentication timeouts will need to be set prior to running `run_command` with `ParallelSSHClient(timeout=<..>)` and/or with socket/OS level timeout settings.

**Comment by pkittenis** [comment]
This seems to have been same issue as #104 . Please re-open with steps to reproduce if not.
