### ISSUE TITLE
SSH shells hang on user input

### ISSUE THREAD

**Issue by mrlexley** [ParallelSSH/parallel-ssh#107]
I really like the pssh client. It's fast and great to work with exit codes instead of expect scripts. But I have the following problem. I can't get passed on devices with a welcome banner where the use need to send a keystroke to continue. Is there any way to get passed this of send a virtual keystroke?

**Comment by pkittenis** [comment]
Hi there,

Thanks for the interest.

The `stdin` channel can be used to send input to the remote host. Eg:

```
output = client.run_command(..)
for host, host_out in output.items():
    stdin = host_out.stdin
    stdin.write('my input\n')
    stdin.flush()
    <..>
```

See also [Using Standard Input](http://parallel-ssh.readthedocs.io/en/latest/quickstart.html#using-standard-input) in the documentation.
