### ISSUE TITLE
Support interactive shells

### ISSUE THREAD

**Issue by ghost** [ParallelSSH/parallel-ssh#114]
**Feature Request**
I've read through examples and the current ParallelSSH can
-  execute a command with different arguments
-  execute different commands on different hosts

What's missing is the ability to execute multiple commands on each host and perhaps group the output to each host.

**_Example:_**
```
hosts = ['server1', 'server2', 'server3']
cmds = ['date', 'uptime', 'pwd']
output = client.run_command (cmds)
```

**Current Work-Around State:**
```
client = ParallelSSHClient (hosts, user = username, password = password)
data = [client.run_command(cmd) for cmd in cmds]
for entry in data:
    for host, host_output in entry.items ():
        print (host)
        for line in host_output.stdout:
            print (line)
```

**Actual Output:**
```
server1
Tue Apr  3 00:03:11 UTC 2018
server2
Tue Apr  3 00:03:11 UTC 2018
server3
Tue Apr  3 00:03:11 UTC 2018
server1
00:03:12 up 7 days, 15:27,  1 user,  load average: 0.00, 0.00, 0.00
server2
00:03:12 up 2 days, 15:27,  1 user,  load average: 0.00, 0.00, 0.00
server3
00:03:12 up 9 days, 15:27,  1 user,  load average: 0.00, 0.00, 0.00
server1
/home/username
server2
/home/username
server3
/home/username
```

It's not the prettiest nor do I entertain the idea of 3 nested for-loops that defeated the purpose of parallel-SSH with each loop eating into the performance.  If there's a better way to implement this, let me know or if it doesn't exist, please implement it.

**Preferred Output:**
```
server1
Tue Apr  3 00:03:11 UTC 2018
00:03:12 up 7 days, 15:27,  1 user,  load average: 0.00, 0.00, 0.00
/home/username

server2
Tue Apr  3 00:03:11 UTC 2018
00:03:12 up 2 days, 15:27,  1 user,  load average: 0.00, 0.00, 0.00
/home/username

server3
Tue Apr  3 00:03:11 UTC 2018
00:03:12 up 9 days, 15:27,  1 user,  load average: 0.00, 0.00, 0.00
/home/username
```

**Comment by pkittenis** [comment]
Hi there,

Thanks for the interest and feature request.

One option is, as shown above, to run individual commands separately. Performance wise there is not much overhead as all commands are executed asynchronously whether they were started together or one after the other. 

That overhead is the same whether the starting of commands is done client side or by parallel-ssh itself.

The other option is to run multiple commands together per server, eg:

```
hosts = ['server1', 'server2', 'server3']
cmd = ';'.join(['date', 'uptime', 'pwd'])
output = client.run_command (cmd)
```

This gives the desired output. The three commands are however executed serially per host. How to run the commands also depends on the users' shell.

I think adding a convenience function for running multiple commands per host in parallel and simplifying output gathering would be useful - it's not the first time it has been asked. The output generators can be chained together to give combined output.

However, it is worth pointing out that this will not yield any performance benefit over a client-side function that does the same thing.
