### ISSUE TITLE
Allow multiple ports on the same host via host_config

### ISSUE THREAD

**Issue by maxux** [ParallelSSH/parallel-ssh#118]
Hello,

I maybe missed something but when trying to reach multiple target, they are always identified by the host. Which means you can only have one connection per host.

In my case, I try to reach some machines behind NAT. Different machines are pointed by different ports, but all on the same host of course.

Even by using a 'host_config', it's again specified by host. One easy way would allows to specify the remote-address on the config dictionary. (eg: like `HostName` in ~/.ssh/config)

I can reach my goal by instanciating one ssh per client by providing each time the host and port, but I loose the efficiency of parallelism.

**Comment by pkittenis** [comment]
Hi there,

Thanks for the interest. Multiple identical hosts can be passed in host list, but yes currently they can only use the same port. HostName as per `.ssh/config` does not help either because that is also per-host. It allows you to have multiple identical hostname entries, but only one will be used. For the paramiko client, `.ssh/config` is used already but has the above limitation.

Perhaps the best solution would be to allow `(host, port)` tuples as entries in host list. So the following becomes possible:

```
hosts = [('localhost', 22), ('localhost', 2222), <..>]
client = ParallelSSHClient(hosts)
<..>
```

That is a simple enough change to make for next release. PRs welcome of course.

**Comment by maxux** [comment]
> HostName as per .ssh/config does not help either because that is also per-host.
I don't think so. Using this config:
```
Host node1
    HostName my.domain.tld
    Port 1000

Host node2
    HostName my.domain.tld
    Port 1001
```
I can `ssh node1` and `ssh node2`, they both connect to `my.domain.tld` respectivly to port 1000 and 1001. The name after `Host` is not necessary the same hostname.

Anyway, your solution about tuple looks fine to me ! :)

**Comment by pkittenis** [comment]
I mispoke - for an `.ssh/config` like the above the port as configured in the config is already used. It is only `host_config` that does not allow this as it is keyed per hostname. Note - paramiko client only currently.

What is missing is a programmatic method without ssh config.

For the above config, output object looks like this:

```
{'node1': 
    host=node1
    <..>,
 'node2'
    host=node2,
    <..>,
}
```

Using port as defined in config.

**Comment by CaselIT** [comment]
[Here](https://github.com/CaselIT/pssh-cli/blob/master/host_file.py#L4) hacked the support by overriding the str class so that I could add the same host twice in the dict, but that's hardly the best solution

> Perhaps the best solution would be to allow (host, port) tuples as entries in host list. So the following becomes possible:
> ...
> That is a simple enough change to make for next release. PRs welcome of course.

Why not adding support for a list like of `dict` instead with a required `host` key would be required. This way all the options would be allowed

**Comment by pkittenis** [comment]
That's a good idea. Ideally there would be only one way to provide per-host configuration for ease of use and API simplicity.

So the above is a good option for replacing `host_config` - though would better use a new `HostConfig` or similar class with `__slots__` instead of dict. List of dicts will very quickly consume lots of memory for large number of hosts.

Eg:

```
hosts = [HostConfig(host='host1', port=22),
         HostConfig(host='host1', port=2222)]
client = ParallelSSHClient(hosts)
```

**Comment by CaselIT** [comment]
Yes, I also thought about it.
Why not use a named tuple tough? The syntax would be the same as your example.

> That's a good idea. Ideally there would be only one way to provide per-host configuration for ease of use and API simplicity.

Yes, using this type of per-host configuration, would make `host_config` redundant

**Comment by pkittenis** [comment]
Yup, namedtuple is good too. Would like to sub-class it to add docstrings for API documentation though as it by default does not allow for docstrings to be manipulated.

**Comment by CaselIT** [comment]
You are right, adding doctrings to named tuples was a hassle until [python 3.6](https://docs.python.org/3/library/typing.html?highlight=namedtuple#typing.NamedTuple)

I guess in the meantime a class with __slots__ is better since it supports docstring

**Comment by Tysher** [comment]
I have a similar requirement, but concerning users.
In my context, for a few cases, different users on the same host represent different environments that I need to connect to.

I'm trying to migrate from Fabric to parallel-ssh, which I find much cleaner and with better documentation, but this incompatibility might make that impossible =(

**Comment by pkittenis** [comment]
Hi @tysher, 

Thanks for the interest. The above proposed solution fits that use case as well and I'm keen to make such migrations feasible.   

I can pull it forward for the 1.10 release but there is no ETA on it, depends on free time. There is no funding for this work unfortunately. 

Pull requests are always welcome.

**Comment by CaselIT** [comment]
@Tysher I've managed to do something similar, but it's an hack based on the current implementation.

I override the str `__eq__` method so it returns `True` only if two string are the same object. 
This allows specifying multiple configuration with the same host address in the `host_config` dict


example:
```py

class CustomString(str):
    '''Allow different configurations on the same host'''

    def __eq__(self, other):
        return self is other

    def __hash__(self):
        return id(self)

hostConfig = {
    # first port in host "ip"
    CustomString('ip'): {},
    # second port in host "ip"
    CustomString('ip'): {}
}

ParallelSSHClient(list(hostConfig.keys()), host_config=hostConfig)
```
This is where I use it: https://github.com/CaselIT/pssh-cli

**Comment by Tysher** [comment]
Wow I wasn't expecting an answer so soon =D
Thank you for your feedback, I was able to use a workaround based on capitalizing certain letters on the host string, making them different entries on the dictionary.

I'm a proud user of your library and from my benchmarks you have already saved me around 9 min in some daily tasks, compared with Fabric, which is amazing to me.

Thank you for your great work!

PS: If I start delving deeper into the code I might venture into collaborating on a few interesting features for ParallelSSH =)

**Comment by pkittenis** [comment]
Targetting `2.0.0` for this as it is a backwards incompatible API change.

* Add HostConfig class
* Make `host_config` option a list of `HostConfig`.

**Comment by pkittenis** [comment]
Done in #215
