### ISSUE TITLE
Native clients returns 127.0.0.1_* as host when using proxy

### ISSUE THREAD

**Issue by tiagom62** [ParallelSSH/parallel-ssh#120]
### Bug reports

__Steps to reproduce:__
Using the native client run a command on a remote host using a proxy. 

1. Example code that produces error.
```
from pssh.clients import ParallelSSHClient
import os

client = ParallelSSHClient(['a.example.com', 'b.example.com'], allow_agent=False, user='ubuntu', pkey=os.path.expanduser('~/.ssh/key'), proxy_host='proxy.example.com', proxy_user='user', proxy_pkey=os.path.expanduser('~/.ssh/id_rsa'))

cmd_response = client.run_command('lsb_release -r', stop_on_errors=False, shell='bash -c')

for node in cmd_response:
    print(cmd_response[node]['host'])
```
2. Stack trace or error messages.
None

__Expected behaviour:__ [What was expected to happen.]
Printed hosts should be:
a.example.com
b.example.com

__Actual behaviour:__ [What actually happened.]
Instead get:
127.0.0.1_fwwa0qmo
127.0.0.1

__Additional info:__ [Include version of ``ssh2-python`` and/or ``paramiko`` and any other relevant information.]
Parallel-ssh 1.6.0
ssh2-python 0.13.0.post2

**Comment by pkittenis** [comment]
Hi there,

Thank you for the interest and report! Resolved in ``1.6.1``.
