### ISSUE TITLE
Run commands over an interactive channel

### ISSUE THREAD

**Issue by pkittenis** [ParallelSSH/parallel-ssh#125]
### Feature Request

* Provide an alternative to `run_command` that uses a single interactive channel for all commands.

This provides a performance boost when running multiple commands one after another as opening/closing channels is the second most time consuming operation, after authentication.

Probably worth doing together with #114

**Comment by flavius** [comment]
Any progress on this?

Reusing the channel while still being able to tell apart the outputs (stdout, stderr and exit code) of each command would be great.

**Comment by flavius** [comment]
`execute` accepts a channel parameters, but reusing it when executing multiple commands makes it wait indefinitely while attempting to run the second command. Also, there is a test `test_execute` which doesn't actually test `execute`, and there is literally no example about how to reuse the channel. The documentation is poor.

Maybe we can just get an example for a workaround in the current version, until v2 is ready?

**Comment by pkittenis** [comment]
Same channel cannot be reused for more than one `execute` command per SSH protocol. There are no examples because it is not possible.

The channel object is available on all clients as well as output objects, so clients can call `channel.shell()` and write commands manually to an interactive shell. This will not give separate output streams, that also needs to be handled in code. Providing an example of this is literally implementing this feature. PR welcome.

Regarding [execute test](https://github.com/ParallelSSH/parallel-ssh/blob/master/tests/test_native_single_client.py#L47), it is calling `run_command` which calls `execute` and that is what is being tested. What do you suggest the test should be doing?

The [public API is fully documented](https://parallel-ssh.readthedocs.io/en/latest/api.html) and most developers are able to extend functionality when needed based on that information. Suggestions and PRs are always welcome.

**Comment by flavius** [comment]
There should be a test which shows how to use the parameter `channel` of the execute method.

**Comment by pkittenis** [comment]
The tests are for testing implementation, not as user code examples.

There [is function](https://parallel-ssh.readthedocs.io/en/latest/native_single.html#pssh.clients.native.single.SSHClient.open_session) to open a channel, which execute takes as param. I'd expect most developers to be able to work with the documented API as-is, without specific examples for every function. PR welcome if you feel a specific example would be useful. Any further on this should be on the mail group, this is an issue for tracking feature implementation.

**Comment by flavius** [comment]
Tests are the best kind of documentation, runnable documentation, easier to keep in sync with the production code. Always, everywhere. And since you're an #$%$: Everyone knows this.

So if `execute` is an implementation detail, then remove it from the documentation. Not for my sake, for the sake of future users of your library. The fact that the public API accepts a `channel` parameter.

If, on the other side, the `channel` parameter is intended for public use, then documentation should be provided. The best-in-class documentation we've got as professional programmers is tests.

Also, learn to manage your open-source project and how to lead discussions. Forget the "PR welcome" mantra, it doesn't do you any good. Good luck with your personal development, I'm out.

**Comment by pkittenis** [comment]
See [Code of Conduct](https://github.com/ParallelSSH/parallel-ssh/blob/master/.github/code_of_conduct.md#our-standards). Abuse will not be tolerated.

As with all open source projects, work is done on a volunteer basis by people offering their free time. If there is something missing that someone wants and is sufficiently motivated to do they are more than welcome to.

All open source projects will say the same thing. Want something done quickly - roll up your sleeves and get going. Expect work for free and tell people with abusive language what to do.. good luck with that.

**Comment by pkittenis** [comment]
Duplicate of #114
