### ISSUE TITLE
support for dynamic port forwarding?

### ISSUE THREAD

**Issue by pttdev** [ParallelSSH/parallel-ssh#126]
I would like to create a socks5 using dynamic port forwarding. I managed to do that with assynssh library but has no clue with parallel-ssh. I will be great if anyone can show me the way. Thank you very much!

**Comment by pkittenis** [comment]
Out of scope for parallel-ssh as its only usable for a single remote host. Use [ssh2-python](http://ssh2-python.readthedocs.io/en/latest/session.html#ssh2.session.Session.direct_tcpip_ex) directly.

Also, these type of questions are better asked on the mail group.
