### ISSUE TITLE
Parallel-SSH fro Windows clients 

### ISSUE THREAD

**Issue by gm0neyl0ve** [ParallelSSH/parallel-ssh#129]
Is it expected that Parallel-SSH would work on Windows SSH Clients?

We have SSH installed on our Windows instances and would like to utilize Parallel-SSH for some tasks. 
The code examples have worked great for our Linux instances, but I'm struggling to get Win targets going.  Any advice/help? 

```python
from __future__ import print_function
#from pssh.clients import ParallelSSHClient
from pssh.clients.miko import ParallelSSHClient

hosts = ['host1']
cmd = 'dir c:'

client = ParallelSSHClient(hosts)

output = client.run_command(cmd)
for host, host_output in output.items():
    for line in host_output.stdout:
        print(line)

Traceback (most recent call last):
  File "/home/bin/Python/parallelssh-win.py", line 34, in <module>
    output = client.run_command(cmd)
  File "/usr/lib64/python2.7/site-packages/pssh/clients/native/parallel.py", line 220, in run_command
    greenlet_timeout=greenlet_timeout)
  File "/usr/lib64/python2.7/site-packages/pssh/clients/base_pssh.py", line 96, in run_command
    self.get_output(cmd, output, timeout=greenlet_timeout)
  File "/usr/lib64/python2.7/site-packages/pssh/clients/base_pssh.py", line 141, in get_output
    (channel, host, stdout, stderr, stdin) = cmd.get(timeout=timeout)
  File "/usr/lib64/python2.7/site-packages/gevent/greenlet.py", line 480, in get
    self._raise_exception()
  File "/usr/lib64/python2.7/site-packages/gevent/greenlet.py", line 171, in _raise_exception
    reraise(*self.exc_info)
  File "/usr/lib64/python2.7/site-packages/gevent/greenlet.py", line 534, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/lib64/python2.7/site-packages/pssh/clients/native/parallel.py", line 234, in _run_command
    raise ex
ssh2.exceptions.ChannelRequestDenied
```

If I switch to this client:
from pssh.clients.miko import ParallelSSHClient

I end up with:
'$SHELL' is not recognized as an internal or external command,
operable program or batch file.

if I ssh to host and test, all works as expected.

 ssh host1 "dir c:"
 Volume in drive C has no label.
 Volume Serial Number is 140A-03D2
<snip>

**Comment by pkittenis** [comment]
Hi there,

Thanks for the interest and report. Windows *clients* are supported, servers no, never been tested. It really depends on the libraries used and the server implementation.

For the paramiko client try:

```python
from pssh.clients.miko import ParallelSSHClient

hosts = ['host1']
cmd = 'dir c:'

client = ParallelSSHClient(hosts)

output = client.run_command(cmd, use_shell=False)
for host, host_output in output.items():
    for line in host_output.stdout:
        print(line)
```

That avoids the use of `$SHELL`. Probably good to have `use_pty=False` too.

It's odd the libssh2 client does not work, it sounds like authentication is passing but `open_session` is denied. Server logs might have some information, if there are some.

**Comment by gm0neyl0ve** [comment]
Thanks! I will give a try ASAP and report back.

**Comment by gm0neyl0ve** [comment]
Confirmed your solution works.
Much appreciated.
