### ISSUE TITLE
libssh2 embedded source code and auto build on from source installations

### ISSUE THREAD

**Issue by delandtj** [ParallelSSH/parallel-ssh#136]
not all dependencies are properly brought in.  it's a requirement that libssh.h exists.... so the build fails.

this can be fixed by making sure "apt-get install libssh2-1-dev" is done before the install... but that defeats the object of the exercise.  it would be best for parallel_ssh to have proper dependency listing and to obtain all required dependencies and check properly if they were already installed (be a good citizen when installing on debian, not overwrite debian packages etc.)

**Comment by delandtj** [comment]
pip3 install of pycapnp does downloading of its dependencies (if they don't exist or if building fails).  maybe a good one to take a look at, see what gives?

**Comment by pkittenis** [comment]
Hi there,

Thanks for the interest and report.

What version of python3 is this being install on? Can you show output of `pip3 install parallel-ssh`?

Would agree that the library can embed and build `libssh2` source code, however, `libssh2` it self has dependencies like openssl that will need to be satisfied externally for reasons that should be obvious - openssl changes frequently and should not be embedded in this project. 

And no, pip will not run system package installations, it is not its job. Binary wheels are provided for all python versions 2.7 >= 3.6 - 3.7 not yet for linux and that is the recommended installation method.

Will leave open to track `libssh2` embed and build and also some better documentation on building from source.

**Comment by pkittenis** [comment]
Bundled `libssh2` added to `ssh2-python`. `parallel-ssh` dependency removed as of `1.9.0`.
