### ISSUE TITLE
Not execute .profile and .bashrc

### ISSUE THREAD

**Issue by estevopaz** [ParallelSSH/parallel-ssh#138]
Hi,

A normal SSH connection with same user and same keys, load bash by default and execute ~/.profile
Here I modify the PATH to add ~/bin and ~/.local/bin

The problem is that with ParallelSSH I miss the profile load, I don't understand why this different behavior which was a bit painful find it.

Here my problem in detail:

    ssh_client.run_command('echo "{}" >> /tmp/test'.format(datetime.datetime.utcnow()))
    ssh_client.run_command('echo $PATH >> /tmp/test')
    ssh_client.run_command('ps -p $$ >> /tmp/test')

/tmp/test:

    2018-09-05 09:35:17.002894
    /usr/local/bin:/usr/bin:/bin:/usr/games
      PID TTY          TIME CMD
    17597 ?        00:00:00 bash

.profile:

    # set PATH so it includes user's private bin if it exists
    if [ -d "$HOME/bin" ] ; then
        PATH="$HOME/bin:$PATH"
    fi
    if [ -d "$HOME/.local/bin" ] ; then
        PATH="$HOME/.local/bin:$PATH"
    fi

Tested versions:

    parallel-ssh            1.6.3
    ssh2-python             0.14.0
    ---
    parallel-ssh            1.8.0.post1
    ssh2-python             0.15.0.post9

Thanks for your time, best,
Estevo.

**Comment by estevopaz** [comment]
I fixed temporally the problem adding these lines to my code:

    # ParallelSSH doesn't load .profile, so we must ensure user local paths manually
    for path in ('/home/{user}/bin', '/home/{user}/.local/bin'):
        path = path.format(user=SSH_USER)
        command = ('if [ -d "{path}" ] && [[ ! $PATH = *"{path}"* ]] ; then'
                   ' PATH="{path}:$PATH; fi && {command}'
                   .format(path=path, command=command))

**Comment by pkittenis** [comment]
Hi there,

Thanks for the interest and report.

Probably want to put that in `.bashrc` and not `.profile`.

Per bash(1) man page, `~/.profile` is only executed on _interactive_ shells, which `parallel-ssh` commands are not. It is also not executed when using the `ssh` binary with a remote command argument - this is the same behaviour as `parallel-ssh`. 

`~/.bashrc` OTOH is always executed when the shell's stdin is connected to a network connection like via sshd and for all non-login interactive shells like when executing bash in an existing login session.

See `man bash` for more info, relevant section below:

> When  bash  is invoked as an interactive login shell, or as a non-interactive shell with the --login option, it first reads and executes commands from the file  /etc/profile,  if  that  file  exists.   After  reading  that  file,  it  looks  for  ~/.bash_profile, ~/.bash_login,  and  ~/.profile, in that order, and reads and executes commands from the first one that exists and is readable.  The --noprofile option may be used when the shell is started to inhibit this behavior.

**Comment by estevopaz** [comment]
I also tried with <pre>.bashrc</pre>, so what I described above for <pre>.profile</pre> is also applied to <pre>.bashrc</pre>.

**Comment by pkittenis** [comment]
Hm, cannot seem to replicate that behaviour:

```
$ cat ~/.bashrc 
#!/bin/bash
export PATH=$PATH:my_dir
echo "From bashrc"

client = ParallelSSHClient(['localhost'])
output = client.run_command('echo $PATH')
for host, host_out in output.items():
     for line in host_out.stdout:
         print(line)
```

Output:

```
From bashrc
/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:my_dir
```

Both the `echo` and modified `$PATH` from `.bashrc` were executed, but not `.profile`. Same behaviour as `ssh localhost "echo $PATH"`

It should be the case that `ssh localhost <cmd>` works the same as `client.run_command(<cmd>)` - if it is not, that is an issue with the library. But I cannot replicate what is described above. Do you not get the same behaviour as with `ssh`?

**Comment by pkittenis** [comment]
Cannot replicate with either client using the above test case - closing. Can only assume that the conditional in `.bashrc` is failing and path is not being updated at all.

Should be able to see that `parallel-ssh` behaviour is the same as doing `ssh localhost "echo $PATH"` - it is with the above test case:

```
ssh localhost "echo $PATH"

From bashrc
/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:my_dir
```

To be re-opened if @estevopaz can show a test case that can reproduce the issue.
