### ISSUE TITLE
Anyhow to use parallel-ssh as interactive

### ISSUE THREAD

**Issue by HenGold** [ParallelSSH/parallel-ssh#147]
Hi
i read the readme file but i was wondering
is any way to use this perfect library to run several commands in single ssh session?

example:
```
Command: pwd
output: /home/user
Command: mkdir test
Command: cd test
Command: pwd
output: /home/user/test
```

Thanks

**Comment by pkittenis** [comment]
Hi there,

This will do the above:

`run_command('pwd; mkdir test; cd test; pwd')`

And is faster than interactive shells. Also gives you correct exit code for last command.

Multiple calls to `run_command` will use a new channel in same authenticated session. Opening channels is cheap in the native client, though any changes of directory or anything like that will not apply to subsequent commands.

For using a single interactive shell can watch #125
