### ISSUE TITLE
SFTP upload can write duplicate data to remote file without stopping

### ISSUE THREAD

**Issue by auqf** [ParallelSSH/parallel-ssh#148]
### Directions

_Issue tracker is for actionable bug reports, issues with the code and feature requests._
_For general questions please use the [mail group](https://groups.google.com/forum/#!forum/parallel-ssh)._
_Remove this section and everything on and above this line._

### Bug reports

__Steps to reproduce:__

1. Example code that produces error.
2. Stack trace or error messages.

__Expected behaviour:__ [What was expected to happen.]

__Actual behaviour:__ [What actually happened.]

__Additional info:__ [Include version of ``ssh2-python`` and/or ``paramiko`` and any other relevant information.]

![image](https://user-images.githubusercontent.com/8895540/47421644-9e509880-d7b3-11e8-8bbd-ca5e45d8a20c.png)

![image](https://user-images.githubusercontent.com/8895540/47421656-a577a680-d7b3-11e8-8066-68019a2bb6a6.png)
![image](https://user-images.githubusercontent.com/8895540/47421676-b0cad200-d7b3-11e8-8bdd-ce7dc36c1a57.png)
why the file is always increasing the size ....

**Comment by pkittenis** [comment]
Hi there,

Thanks for the interest and report..

What issue is being reported exactly? That `copy_file` appends to destination file on each call to `copy_file`? 

Code to replicate the issue will need to be shown and in text, not pictures. From the above, `copy_file` is only called once. Was it run again?

In any case, cannot reproduce what is shown above. Destination file gets overwritten if it exists, as expected. Will also note file size does not match only on one file shown above.

Will also need to include basic information, the things in the issue template above that were not completed. At least:

* Version used
* Code to reproduce the issue
* Platform client is running on. Specifically which version of windows is client run from.

Are needed for any investigation to happen. Thank you.

**Comment by auqf** [comment]
1.the version is the master of the github.
2.I run it on the windows10, and the version of python  is 2.7.
3.the demo code as the follows:
#! /usr/bin/env python

from pssh.clients import ParallelSSHClient
from pssh.utils import enable_logger, logger
from gevent import joinall

enable_logger(logger)
hosts = ['192.168.1.189']
client = ParallelSSHClient(hosts,user='root', password='auqf')
src = r'D:\build\test3'
dst ='/tmp'
cmds = client.copy_file(src, dst,recurse=True)
#cmds = copy_remote_file(src, dst, recurse=True)
joinall(cmds, raise_error=True)

**Comment by auqf** [comment]
in the source directory, there are many files. And after I upload two files, I found there is a file is increasing the size, and it's not my expect. then I force break the script.

**Comment by alexyr** [comment]
Same here:
<pre>
from pssh.clients.native import SSHClient
from datetime import datetime

host = 'host'
client = SSHClient(host, user='test', password='test', port=22)

start = datetime.now()
print(start)

client.copy_file('Z:/ftp_test', 'ftp-test', recurse=True)

end = datetime.now()
print(end)
print(end - start)
</pre>

Each time it is stuck on dll file, which grows until I kill the test script...
If I delete that file, next run it will stuck on next dll found!

**Comment by pkittenis** [comment]
Have confirmed there is a bug here.

It also happens on prior releases of parallel-ssh and ssh2-python.

There also seems to be an issue with SCP functionality where incomplete files are written that will investigate also. There seems to be a logic error when handling incomplete writes that would block and need to be resumed - will know more once it can be reliably reproduced.

In meantime if this is a blocker for you can use the paramiko based client `from pssh.clients.miko` - though keep in mind the paramiko library is very buggy hence being deprecated.

**Comment by pkittenis** [comment]
Hi,

The `1.9.1` release contains fixes for this issue and have confirmed that it no longer happens from a windows client as well where it would appear the most. If you can you confirm this is also the case for you that would be very useful.

Thanks for reporting this, it was quite a hard to replicate bug and affected all writes via the native client including SCP, SFTP and proxy implementation.
