### ISSUE TITLE
Feature request: timeout option for open_session

### ISSUE THREAD

**Issue by tsarvela** [ParallelSSH/parallel-ssh#149]
### Feature request

The asynchronous functionality of parallel-ssh is very much appreciated for management tasks. Thank you for this!

For the feature request:

It seems that the open_session() can keep worker allocated for much longer than expected in failure cases. Would it be reasonable to stretch the timeout option of wait_socket() to open_session() ?

**Comment by pkittenis** [comment]
Hi there,

Thanks for the interest and report!

Yes, it looks like timeout is not passed on to `open_session` and would be good to add. 

PRs always welcome if anyone is up for it, or can wait for next release.
