### ISSUE TITLE
Concurrency issue with multiple channels

### ISSUE THREAD

**Issue by tsarvela** [ParallelSSH/parallel-ssh#151]
### libssh2 segfault/assertion error with concurrent open_sessions

The issue can be reproduced with the following code:
`
#!/usr/bin/env python3

from ssh2.session import Session

import os
import socket
import threading
import time

def demo(sess):
    success = False
    while not success:
        try:
            chan=sess.open_session()
            chan.execute('sleep 10')
            print(chan, flush=True)
            success = True
        except:
            time.sleep(0.1)

sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
sock.connect(('127.0.0.1', 22))

sess = Session()
sess.handshake(sock)
sess.agent_auth(os.getlogin())

for i in range(0,10):
    t=threading.Thread(target=demo, args=(sess,))
    t.start()
    print(t, flush=True)
time.sleep(300)
sess.disconnect()
`
Expected behaviour would be 10 concurrent "sleep 10" processes on localhost.

Actual behaviour is usually 0-3 threads successfully executing "sleep 10" on localhost before libssh2 segmentation fault, assertion error. Sometimes the failure is silent with less threads than expected.

As a comparison, similar code with paramiko works as expected:
`
#!/usr/bin/env python3

import os
import paramiko
import threading
import time

def demo(client):
    success = False
    while not success:
        try:
            chan=client.get_transport().open_session()
            chan.exec_command('sleep 10')
            print(chan, flush=True)
            success = True
        except:
            time.sleep(0.1)

key = paramiko.RSAKey.from_private_key_file(os.path.expanduser('~')+'/.ssh/id_rsa')
client=paramiko.SSHClient()
client.load_system_host_keys()
client.set_missing_host_key_policy(paramiko.MissingHostKeyPolicy())
client.connect(hostname='localhost', username=os.getlogin(), pkey = key)

for i in range(0,10):
    t=threading.Thread(target=demo, args=(client,))
    t.start()
    print(t, flush=True)
time.sleep(300)
client.close()
`
Versions used are newest that pip found: ssh2-python 0.17.0 and paramiko 2.4.2

**Comment by pkittenis** [comment]
Hi there,

Thanks for the interest.

Couple things:

* The above is not related to parallel-ssh. ssh2-python is a separate project.
* libssh2 sessions cannot be shared across threads. Segfaults are expected when they are.
* There is no need to use all that code with parallel-ssh.

The equivalent in parallel-ssh works as expected and with higher performance as it does not use threads:

```
from pssh.clients import ParallelSSHClient

hosts = ['127.0.0.1' for _ in range(10)]
client = ParallelSSHClient(hosts)
client.join(client.run_command('sleep 10'))
```

**Comment by tsarvela** [comment]
Hi,

The code provided was only an example. In real use case all the commands
would be very different, so parallel-ssh won't help me in this case.

I probably filed the bug under wrong project, due to lack of coffee this
morning. Apologies for that.

Tomi

**Comment by pkittenis** [comment]
Hi,

No worries. parallel-ssh supports running different commands on a per host basis - [see documentation](https://parallel-ssh.readthedocs.io/en/latest/advanced.html#per-host-command-substitution).

```
output = client.run_command('%s', host_args=(
    'host1_cmd', 'host2_cmd', 'host3_cmd'))
client.join(output)
<..>
```

If there is a use case for running commands in parallel via SSH that this project does not already cater to please raise a feature request for it with an example use case. As the name suggests, that is the purpose of this project.

**Comment by pkittenis** [comment]
There is functionality to log, read output, get exit codes etc for all individual commands. Multiple parallel clients per batch of commands or similar is also suitable. Struggle to think what would be possible with threads that is not possible already in parallel-ssh. Plus parallelisation of I/O with threads does not scale - hence why parallel-ssh uses non-blocking I/O with an event loop library.

But it's up to you. If you'd rather use ssh2-python directly go ahead - just do not share sessions across threads. Each thread must create its own session.
