### ISSUE TITLE
Password authentication failed raise

### ISSUE THREAD

**Issue by whuizhe** [ParallelSSH/parallel-ssh#152]
When one or more password errors occur, the program exits. It would be
This will affect the execution of other correct passwords

## Change "raise" to "return"
#path ./python3.6/site-packages/pssh/clients/base_pssh.py

```
def get_output(self, cmd, output, timeout=None):
        try:
            (channel, host, stdout, stderr, stdin) = cmd.get(timeout=timeout)
        except Exception as ex:
            host = ex.host
            self._update_host_output(
                output, host, None, None, None, None, None, cmd, exception=ex)
            raise
        self._update_host_output(output, host, self._get_exit_code(channel),
                                 channel, stdout, stderr, stdin, cmd)

```

**Comment by pkittenis** [comment]
Hi there,

Thanks for the interest and report.

Suppressing exceptions can be done with `run_command(<..>, stop_on_errors=False)`. [See documentation](https://parallel-ssh.readthedocs.io/en/latest/native_parallel.html#pssh.clients.native.parallel.ParallelSSHClient.run_command).

If there is an issue being reported please show code to reproduce and can re-open.
