### ISSUE TITLE
LGPL version clarification

### ISSUE THREAD

**Issue by dsuch** [ParallelSSH/parallel-ssh#154]
Hello,

in reference to ticket #5 which changed the library's license from GPL to LGPLv2 back in 2014, I would like to ask if it was possible for you to change it to "LGPLv2 or LGPLv3"?

The context is that I would like to try out the usage of parallel-ssh in [Zato](https://zato.io/docs/) but Zato is under LGPLv3.

I can see why making it open-ended in a way that "LGPLv2 or later" expresses it may be too much, seeing as one can not anticipate what a hypothetical LGPLv4 could introduce, but LGPLv3 is a well-known license that will not change so perhaps this would be feasible.

Could you please let me know what your thoughts on it are?

Regards.

**Comment by pkittenis** [comment]
Hi there,

Thanks for the interest. No, the license is LGPLv2.1 only and that is deliberate.

LGPLv2.1 can be combined with v3, though any derivative works would need to be published under GPLv3. Simply for use/linking there are no restrictions. See https://www.gnu.org/licenses/gpl-faq.html#gpl-compat-matrix
