### ISSUE TITLE
passwordless authentication in pssh.clients.native.single

### ISSUE THREAD

**Issue by sanga** [ParallelSSH/parallel-ssh#158]
Is this possible currently? At least from my reading of the docs etc I couldn't see how it should be done and neither did it work in any of my experimentation

**Comment by pkittenis** [comment]
Hi there,

Thanks for the interest. Is there some code that shows an issue? From [the documentation](https://parallel-ssh.readthedocs.io/en/latest/native_single.html#pssh.clients.native.single.SSHClient):

```
pkey (str) – Private key file path to use for authentication. Path must be either absolute path or relative to user home directory like ~/<path>.
```

For usage questions best use the [google group](https://groups.google.com/forum/#!forum/parallelssh).
