### ISSUE TITLE
My hosts have different users and passwords

### ISSUE THREAD

**Issue by borre47** [ParallelSSH/parallel-ssh#161]
i have tried the next
client=ParallelSSHClient(hosts=['10.0.29.117','200.188.131.165'],user=['javier','alfonsorojas'],password=['22222','22222'])
because my hosts have different users and passwords
error  
if self.session is not None:
AttributeError: 'SSHClient' object has no attribute 'session'
please how can i fix it ?

**Comment by pkittenis** [comment]
Hi there,

Thanks for the interest See [per-host configuration functionality](https://parallel-ssh.readthedocs.io/en/latest/advanced.html#per-host-configuration). For usage questions best use the [users group](https://groups.google.com/forum/#!forum/parallelssh) - this is an issue tracker.
