### ISSUE TITLE
scp_send document

### ISSUE THREAD

**Issue by github-of-dl** [ParallelSSH/parallel-ssh#162]
How can I know that the file is successfully send to remote when I can call `scp_send`?
Will it check file with checksum like md5?

**Comment by pkittenis** [comment]
Hi there,

Thanks for the interest. For usage questions the [mail group](https://groups.google.com/forum/#!forum/parallelssh) is more appropriate - this is an issue tracker.

The library does not do checksums, that will have to be done in code. The transfer is successful unless an exception has been raised.
