### ISSUE TITLE
host_args is not working

### ISSUE THREAD

**Issue by bhaweshintouch** [ParallelSSH/parallel-ssh#163]
hosts1 = ['my.example.com']

client = ParallelSSHClient(hosts1, pkey='./testing.pem')

image2 = '*****.dkr.ecr.ap-south-1.amazonaws.com/%s:dev-latest' % service
pull_cmd = 'docker pull %s' % image2
run_cmd = 'docker run -d -p %s:%s --name %s  --restart always %s' % (port, port, service, image2)
output = client.run_command('%s %s', host_args = ((pull_cmd, run_cmd),))

above is not working, 

but if i call the same command individually it is working, below is working.

output = client.run_command(pull_cmd)
output = client.run_command(run_cmd)

**Comment by pkittenis** [comment]
Hi there,

Thanks for the interest. 

That is not a valid use of `host_args` - have [you seen the examples](https://parallel-ssh.readthedocs.io/en/latest/advanced.html#per-host-command-substitution)?

The above creates a command string `docker pull <image> docker run -d -p <..>` which is not a valid command. If you are trying to run both commands together that would be `run_command(pull_cmd + ';' + run_cmd)` which makes the command string `docker pull <..>; docker run <..>`. Multiple run commands also works and gives separate exit codes.

Host args is for executing different commands on each host in host list. What is the code above intending to do?

**Comment by bhaweshintouch** [comment]
Hi, thanks for replying, i want to execute above two commands(pull_cmd and run_cmd) on multiple hosts. currently i have one host for testing so host list contains only one host. for each host pull_cmd and run_cmd will have different image. i mean for second host i will execute pull_cmd2 and run_cmd2

**Comment by pkittenis** [comment]
Hi,

The command passed in will have to have string substitutions in it [per example](https://parallel-ssh.readthedocs.io/en/latest/advanced.html#per-host-command-substitution), eg:

```
hosts = ['host1', 'host2']
pull_cmd = 'docker pull %s'
host_args = ('host_image_1', 'host_image_2')
client.run_command(pull_cmd, host_args=host_args)
```

And similar for other commands. If the command used for `run_command` does not contain string substitution `host_args` will not work and will raise an exception. The resulting command string from substitution should also be valid.

Best to use mail group for this as it's a usage question.
