### ISSUE TITLE
Update host_config example

### ISSUE THREAD

**Issue by bhaweshintouch** [ParallelSSH/parallel-ssh#164]
Getting error on simple example steps.
host_config = {'my.example.com' : {'user': 'ubuntu', 'private_key': load_private_key(
                              open('mykey.pem'))}
                }
hosts = host_config.keys()
client = ParallelSSHClient(hosts, host_config=host_config)
output = client.run_command('pwd')

**Comment by pkittenis** [comment]
Hi there,

Thanks for interest and report. The example needs updating, it should be:

```
host_config = {'my.example.com' : {'user': 'ubuntu', 'private_key': 'mykey.pem'}}
```

`load_private_key` is only for paramiko clients.

**Comment by pkittenis** [comment]
Documentation updated.
