### ISSUE TITLE
clients.native.single.Client._eagain has not retry limit, so it can hang forever

### ISSUE THREAD

**Issue by sanga** [ParallelSSH/parallel-ssh#166]
https://github.com/ParallelSSH/parallel-ssh/blob/379b8713fa79592b7e45ee4c9b8715efa36e525e/pssh/clients/native/single.py#L378

The while loop in that function can spin infinitely. Probably there should be a retry limit such that the loop will eventually bail out and fail.

Note: this issue was split out of: #157 see comment: https://github.com/ParallelSSH/parallel-ssh/issues/157#issuecomment-473001333

**Comment by pkittenis** [comment]
Thanks for raising. The solution here is to pass on the `timeout` flag to `_eagain`. This is done in [some places](https://github.com/ParallelSSH/parallel-ssh/blob/379b8713fa79592b7e45ee4c9b8715efa36e525e/pssh/clients/native/single.py#L816), but is not consistent.

**Comment by pkittenis** [comment]
This is better handled by greenlet timeout - handling EAGAIN should not fail as that would cause greenlets to terminate unexpectedly. In this case, handling SFTP channel open failure, is already handled by libssh2 and native client.
