### ISSUE TITLE
ParallelSSH with TTY

### ISSUE THREAD

**Issue by masterchop** [ParallelSSH/parallel-ssh#176]
I am trying to append data to file owned by another user. So i need to run it as root to make the change. Unfortunately, i get the following error:

 06/28/2019 04:19:18 PM - pssh.host_logger - INFO - [XX.XX.XX.XX]      [err]
sudo: sorry, you must have a tty to run sudo

I know i can change the sudoers file but its a prod environment and i cant touch anything.

`def AutoFiles(hosts,cmd,UserName,Pass):
    client = ParallelSSHClient(hosts, user=UserName, password=Pass)
    output = client.run_command(cmd)
    #print(output)
    for host in output:
        for line in output[host]['stderr']:
            print(line)

AutoFiles(bo_hosts,'sudo echo "'+tnsdata+'" >> ~/tnsnames.ora',UserName,Pass)`

Is there a way to enable TTY for parallelSSH?

**Comment by pkittenis** [comment]
Hi there,

Thanks for the interest. For usage questions best to use mail group - this is an issue tracker.

See `use_pty=True` flag in [API documentation](https://parallel-ssh.readthedocs.io/en/latest/native_parallel.html#pssh.clients.native.parallel.ParallelSSHClient.run_command).

**Comment by masterchop** [comment]
for some reason when i tried it didnt work so ill give it a try later, thanks. I saw the root option too so i might check that one too. thanks
