### ISSUE TITLE
timeout in native wait_finished() in ms not seconds

### ISSUE THREAD

**Issue by cpeel** [ParallelSSH/parallel-ssh#182]
### Bug reports

Timeout passed to `pssh.clients.native.single.SSHClient.wait_finished()` is in milliseconds not seconds. This is inconsistent with the other API and undocumented.

`pssh.clients.native.single.SSHClient.wait_finished()` takes a timeout value. The docs don't talk about the units for this timeout value. Turns out the timeout is passed to ssh2's `wait_select()` and those times are in milliseconds, not seconds. All of the other timeouts in the parallel-ssh are in seconds, so this makes it an outlier and introduces an inconsistency in the API.

Either the timeout passed to `wait_finished()` should be seconds and converted to ms before passing it into `wait_select()` or the docs need to be updated to reflect that this is in milliseconds. Either way, updating the docs would be a great idea.

__Additional info:__ 
* parallel-ssh==1.9.1
* ssh2-python==0.18.0.post1

**Comment by pkittenis** [comment]
Thanks for the report, would be good to make this consistent. PRs welcome.
