### ISSUE TITLE
scp_send without recurse and destination is a directory fails without useful error

### ISSUE THREAD

**Issue by amentee** [ParallelSSH/parallel-ssh#183]
Hi Team,

I was just beginning to use parallel ssh and want to copy a file from my local system to remote server. Below is the code I have written .

from __future__ import print_function
from pssh.clients import ParallelSSHClient
from gevent import joinall

hosts = ['emdc1ansl01']
client = ParallelSSHClient(hosts, user='xxxx', password='xxxx')
cmds = client.scp_send('version.txt', '/tmp/')
joinall(cmds, raise_error=True)

WHen i execute the above code it throw me below error.

********************************************************
SCPProtocolError                          Traceback (most recent call last)
c:\users\skumar17\downloads\python\lib\site-packages\pssh\clients\native\single.py in _scp_send(self, local_file, remote_file)
    790                 remote_file, fileinfo.st_mode & 0o777, fileinfo.st_size,
--> 791                 fileinfo.st_mtime, fileinfo.st_atime)
    792         except Exception as ex:

SCPProtocolError: 

During handling of the above exception, another exception occurred:

SCPError                                  Traceback (most recent call last)
<ipython-input-17-18ca4c4ed946> in <module>
      4 #output = client.run_command()
      5 cmds = client.scp_send('version.txt', '/tmp/')
----> 6 joinall(cmds, raise_error=True)
      7 #for host, host_output in output.items():
      8 #    for line in host_output.stdout:

**SCPError: ('Error opening remote file %s for writing on host %s - %s', '/tmp/', 'emdc1ansl01', SCPProtocolError())**

**Comment by amentee** [comment]
Please update on how to fix the issue. I am really stuck here

**Comment by ShixiangWang** [comment]
I got the same issue https://github.com/ParallelSSH/ssh2-python/issues/88 from ssh2-python package, could it be explained by a same reason?

**Comment by grmpz** [comment]
It looks like you're missing the target file name, try this:

```
hosts = ['emdc1ansl01']
client = ParallelSSHClient(hosts, user='xxxx', password='xxxx')
cmds = client.scp_send('version.txt', '/tmp/version.txt')
joinall(cmds, raise_error=True)
```

**Comment by pkittenis** [comment]
Code should either raise exception or write to directory with same filename if one is not provided. The latter seems more appropriate.

**Comment by pkittenis** [comment]
Now possible to `scp_send` and `scp_recv` `('source_file', 'target_dir/')` and have file be copied to `target_dir/source_file` per regular SCP.
