### ISSUE TITLE
Allow getting exit code without client.join after exhausting output

### ISSUE THREAD

**Issue by erpadmin** [ParallelSSH/parallel-ssh#191]
### Bug reports

__Steps to reproduce:__
one example below,  i've also ran a simple remote shell script with exit 1 call in it and the exit code is 0

```
from pssh.clients import ParallelSSHClient

host='myhost.localnet'
client = ParallelSSHClient([host], user=someuser)

output = client.run_command('bash -c \"exit 1\"')
for host, host_output in output.items():
    for line in host_output.stdout:
        print(line)

    stderr = ''.join(host_output.stderr)
    if stderr:
        print("STDERR: {}".format(stderr))

    retval = output[host].exit_code
    print("retval: {}".format(retval))

```
__Expected behaviour:__ [What was expected to happen.]
retval should be 1
__Actual behaviour:__ [What actually happened.]
retval is 0

**Comment by erpadmin** [comment]
interestingly this variant works as expected
```
from pssh.clients import ParallelSSHClient

host='myhost.localhost'
client = ParallelSSHClient([host], user='someuser')

output = client.run_command('bash -c \"exit 1\"')
client.join(output)

for host in output:
    retval = output[host].exit_code
    print("retval: {}".format(retval))
```


in the previous example my understanding is that if I iterate ouput then the command has completed execution and the exit_code should be available

**Comment by erpadmin** [comment]
after fully iterating stdout, output[host].exit_code is not automatically updated, but you can call this way instead
```
for host, host_output in output.items():
    for line in host_output.stdout:
        pass # consume all the output
    retval = client.get_exit_code(host_output)
   ...
```
i've had issues with client.join(output) where a problematic host was not responding or hung then it would hang the join call and it wasn't clear who the contributor was.

**Comment by pkittenis** [comment]
Looks like documentation needs updating - ```client.join``` is required for exit codes to work correctly. Or use ```get_exit_code``` as above. Would be good to do this automatically on reading output though.

**Comment by pkittenis** [comment]
As of `1.11.0`, `client.join` is no longer required to get exit code as long as output has been gathered.

Meaning this now works:

```
for host, host_output in output.items():
    for line in host_output.stdout:
        pass # consume all the output
    # host_output.exit_code is not None
    retval = host_output.exit_code
```

`HostOutput.exit_code` is now a dynamic property. `ParallelSSHClient.get_exit_codes` and `get_exit_code` are now no-ops and will be removed in `2.0.0`.

**Comment by gitterspec** [comment]
Related issue... Is there a way to get the exit_code without consuming the output (or consuming it silently without flooding the screen)? Even when I use `pass`, the logger still prints messages. Using `client.join(consume_output=True)` is similarly not silent and setting it to `False` does not return an exit_code.
