### ISSUE TITLE
Prevent logging of stdout/stderr generators when contents of generators are accessed

### ISSUE THREAD

**Issue by HunterAP23** [ParallelSSH/parallel-ssh#193]
### Bug reports

__Steps to reproduce:__

1. Create a logging object like so:
```
import logging as lg
my_log = lg.getLogger()
```
2. Run the `run_command()` function of the native ParallelSSHClient:
```
client = ParallelSSHClient(hosts)
output = client.run_command("echo 'hello'")
```
3. Access the stdout generator, which automatically prints it to the log:
```
for host, out in output.items():
    tmp = ""
    for i in out.stdout:
        tmp = i
```

__Expected behaviour:__ [What was expected to happen.]
stdout should be saved to the tmp variable and not printed to the log.

__Actual behaviour:__ [What actually happened.]
The stdout gets printed to the log. This occurs even if the line `tmp = i` is replaced with `pass`, which means that just accessing the contents of the stdout generator prints the contents to the log.
The issue is that I can't parse the output for commands within python, and the output is directly printed to my logging handlers.

I found mention of removing the logging in issue #29 , but following the instructions there does not work.

I searched and found references to a pretty old paramaeter `return_buffers` for a `get_output` function, but this parameter has since been removed. This is found in issue #4 

I'd like a similar functionality restored so that the stdout and stderr to not get printed when the generators contents are accessed.

This seems to be related to the code in parallel-ssh/pssh/clients/native/single.py on lines 401 to 404:
```
for line in output_buffer:
    output = line.decode(encoding)
    host_logger.info("[%s]%s\t%s", self.host, prefix, output)
    yield output
```

__Additional info:__ [Include version of ``ssh2-python`` and/or ``paramiko`` and any other relevant information.]
Using Python 2.7.5
Parallel-SSH version 1.9.1
ssh2 version 0.18.0.post1

**Comment by HunterAP23** [comment]
#4 
#29

**Comment by pkittenis** [comment]
Hi there,

Thanks for interest.

Can you please show self contained code to reproduce the issue? There seems to be some code somewhere that is enabling ```host_logger``` which then prints output. This is by [design and documentation](https://parallel-ssh.readthedocs.io/en/latest/quickstart.html#host-logger).

Without enabling ```host_logger```, nothing is printed. This is the default.

Suspect there is code after  ```my_log = lg.getLogger()``` that enables logging. ```getLogger``` without a name will give back the root logger. Enabling logging on root logger will enable all loggers, including the ones in parallel-ssh.

```
    for i in out.stdout:
        tmp = i
```
This is also overwriting tmp for each line.

**Comment by pkittenis** [comment]
Looks like client code issue. Host logger is not enabled by default.
