### ISSUE TITLE
Typo in man pages

### ISSUE THREAD

**Issue by trevorbryant** [ParallelSSH/parallel-ssh#198]
### Directions

I hadn't seen (or missed) an issue related to this. There is a typo in the `man` and ubuntu manual pages of this package. In those pages, there are _four_ `L`'s total when there should be three.

Example: 
> $ man parallel-ssh | grep lll
para**lll**el-ssh(1)                                                                                         General Commands Manual                                                                                        para**lll**el-ssh(1)
       para**lll**el-ssh — parallel ssh program
       para**lll**el-ssh [-vAiIP] [-h hosts_file] [-H [user@]host[:port]] [-l user] [-p par] [-o outdir] [-e errdir] [-t timeout] [-O options] [-x args] [-X arg] command ...
       para**lll**el-ssh -I [-vAiIP] [-h hosts_file] [-H [user@]host[:port]] [-l user] [-p par] [-o outdir] [-e errdir] [-t timeout] [-O options] [-x args] [-X arg] [command ...]
       para**lll**el-ssh is a program for executing ssh in parallel on a number of hosts.  It provides features such as sending input to all of the processes, passing a password to ssh, saving output to files, and timing out.
              used more than once), then para**lll**el-ssh behaves as though these files were concatenated together.  If a host is specified multiple times, then para**lll**el-ssh will connect the given number of times.
              Make connections time out after the given number of seconds.  With a value of 0, para**lll**el-ssh will not timeout any connections.
       The exit status codes from para**lll**el-ssh are as follows:
                                                                                                            January 24, 2012                                                                                            para**lll**el-ssh(1)

### Bug reports

__Steps to reproduce:__

1. `man parallel-ssh`
2. [ubuntu manuals](https://manpages.ubuntu.com/manpages/focal/man1/parallel-ssh.1.html)

**Comment by pkittenis** [comment]
Thanks for the interest. Best to raise on the ubuntu bug tracker. That text does not come from this project.
