### ISSUE TITLE
Install failure on Cygwin

### ISSUE THREAD

**Issue by pfedin** [ParallelSSH/parallel-ssh#199]
"pip3 install ssh2-python" currently fails on Cygwin due to a compilation failure. The root cause is attempt to include Windows native headers together with UNIX ones, provided by Cygwin. Modern Cygwin does not allow to freely do that, especially regarding winsock definitions.

The solution is to surround all the checks for these files in CMakeLists.txt with "if(NOT CYGWIN"). E.g.:
if(NOT CYGWIN)
  check_include_files(windows.h HAVE_WINDOWS_H)
  check_include_files(ws2tcpip.h HAVE_WS2TCPIP_H)
  check_include_files(winsock2.h HAVE_WINSOCK2_H)
endif(NOT CYGWIN)

**Comment by pkittenis** [comment]
ssh2-python is a different project. There are from [source installation instructions in its documentation](https://ssh2-python.readthedocs.io/en/latest/installation.html#installation-from-source). On windows C files will need to be re-generated from their Cython sources to include correct headers.
