### ISSUE TITLE
I am getting import error while trying to run the examples

### ISSUE THREAD

**Issue by dinesh3367** [ParallelSSH/parallel-ssh#234]
Traceback (most recent call last):
  File "pssh_local.py", line 23, in <module>
    from pssh import SSHClient, ParallelSSHClient, utils
ImportError: cannot import name 'SSHClient'

What could be missing here ??
I am trying to run the example in ubuntu18.04 with a python3 setup

**Comment by pkittenis** [comment]
`cd` in the examples directory before running them. If the repository is checked out the `pssh` local package will conflict with the installed package.

```
/parallel-ssh/examples $ python parallel_commands.py 
Started 10 commands on 2 host(s) in 0:00:00.148025
<..>
```
