### ISSUE TITLE
Python 2 support in recent releases

### ISSUE THREAD

**Issue by fsaintma** [ParallelSSH/parallel-ssh#247]
### Bug reports

```
___________________________________ ERROR collecting iotlabsshcli/open_a8.py ___________________________________
iotlabsshcli/open_a8.py:25: in <module>
    from iotlabsshcli.sshlib import OpenA8Ssh
iotlabsshcli/sshlib/__init__.py:25: in <module>
    from .open_a8_ssh import OpenA8Ssh
iotlabsshcli/sshlib/open_a8_ssh.py:27: in <module>
    from pssh.clients import SSHClient
.tox/py27-tests/local/lib/python2.7/site-packages/pssh/clients/__init__.py:19: in <module>
    from .native.parallel import ParallelSSHClient
.tox/py27-tests/local/lib/python2.7/site-packages/pssh/clients/native/__init__.py:19: in <module>
    from .parallel import ParallelSSHClient
.tox/py27-tests/local/lib/python2.7/site-packages/pssh/clients/native/parallel.py:20: in <module>
    from .single import SSHClient
.tox/py27-tests/local/lib/python2.7/site-packages/pssh/clients/native/single.py:36: in <module>
    from ..base.single import BaseSSHClient
.tox/py27-tests/local/lib/python2.7/site-packages/pssh/clients/base/single.py:38: in <module>
    from ...output import HostOutput, HostOutputBuffers, BufferData
.tox/py27-tests/local/lib/python2.7/site-packages/pssh/output.py:33: in <module>
    """
E   AttributeError: attribute '__doc__' of 'type' objects is not writable
```

__Expected behaviour:__ 

The python 2 support works in recent releases

__Actual behaviour:__

We wrote a Python library which use Parallel-ssh (thanks for your job). Our library test cases don't work with python 2 due to Parallel-ssh errors. I didn't find in your documentation that you had stopped the Python2 support ? is this the case ?

I just saw that you have circle-ci builds with only Python 3 support. By the way, your documentation (https://parallel-ssh.readthedocs.io/en/latest/) always references old Travis builds.

__Additional info:__ 

parallel-ssh: **2.3.1**
paramiko: **2.7.2**
ssh2-python: **0.25.0**

**Comment by pkittenis** [comment]
Thank you for the interest and report.

Will take a look.

Python 2 is EOL and support will be stopped once upstream stops supporting it (January 2021). That said, have stopped using TravisCI as it no longer works well for me and CircleCI does not support running on python 2 so will not notice py2 failures unless testing manually.

**Comment by gdamich** [comment]
Having similar issue by tying to import:

`Python 2.7.16 (default, Oct 10 2019, 22:02:15) 
[GCC 8.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from pssh.clients import ParallelSSHClient
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pssh/clients/__init__.py", line 19, in <module>
    from .native.parallel import ParallelSSHClient
  File "/usr/local/lib/python2.7/dist-packages/pssh/clients/native/__init__.py", line 19, in <module>
    from .parallel import ParallelSSHClient
  File "/usr/local/lib/python2.7/dist-packages/pssh/clients/native/parallel.py", line 20, in <module>
    from .single import SSHClient
  File "/usr/local/lib/python2.7/dist-packages/pssh/clients/native/single.py", line 36, in <module>
    from ..base.single import BaseSSHClient
  File "/usr/local/lib/python2.7/dist-packages/pssh/clients/base/single.py", line 38, in <module>
    from ...output import HostOutput, HostOutputBuffers, BufferData
  File "/usr/local/lib/python2.7/dist-packages/pssh/output.py", line 33, in <module>
    """
AttributeError: attribute '__doc__' of 'type' objects is not writable
>>> `

**Comment by pkittenis** [comment]
`2.3.2` resolves.

**Comment by fsaintma** [comment]
@pkittenis It works. Many thanks for your work and reactivity.
