### ISSUE TITLE
gevent version

### ISSUE THREAD

**Issue by gdamich** [ParallelSSH/parallel-ssh#269]
**Describe the bug**
It looks that at least on gevent version I'm using (gevent 1.1.2) is yielding error on Timeout object due to missing attribute (1.1.2 is as I can see from 2016, and with this, commit Timeout.close() was introduced: [commit](https://github.com/gevent/gevent/commit/51461c84b5b88ffeabd86955b6e094bf7daaeeba#diff-b24d69286f0fb60ed361ec94b7a5658435fe02fad07f86ab8af1024acc3f8ed8R220)

**To Reproduce**

Steps to reproduce the behaviour:
```
...
output = client.run_command(cmd, use_pty=True, read_timeout=2)

for host_out in output:
    try:
        for line in host_out.stdout:
            print(line)
        for line in host_out.stderr:
            print(line)
    except Timeout:
        pass
```

```
    for line in host_out.stdout:
  File "/usr/local/lib/python2.7/dist-packages/pssh/clients/base/single.py", line 464, in read_output_buffer
    for line in output_buffer:
  File "/usr/local/lib/python2.7/dist-packages/pssh/clients/base/single.py", line 434, in _read_output_buffer
    timer.close()
AttributeError: 'Timeout' object has no attribute 'close'
```

**Expected behaviour**
Well, looking at your requirements and gevent>=1.1, I would expect that issue does not happen.

**Actual behaviour**
the exception from above

**Additional information**
```
# pip list | grep ssh
parallel-ssh                  2.5.1      
ssh-python                    0.9.0      
ssh2-python                   0.26.0 
```

**Comment by pkittenis** [comment]
Hi there,

Thank you for the interest and report.

Minimum gevent version has been updated to resolve this in [2.5.2](https://github.com/ParallelSSH/parallel-ssh/releases/tag/2.5.2).
