### ISSUE TITLE
TypeError with pssh.clients.ssh and password auth

### ISSUE THREAD

**Issue by gennady-voronkov** [ParallelSSH/parallel-ssh#276]
_For general questions please use the [mail group](https://groups.google.com/forum/#!forum/parallel-ssh)._

**Describe the bug**

**To Reproduce**
I have python script, the main lines:
from pssh.clients.ssh import ParallelSSHClient
client = ParallelSSHClient(hosts, user='Administrator', password=''password, port=22, timeout=30)
output = client.run_command(command='ls', user='Administrator', timeout=30)

or
from pssh.clients.ssh import ParallelSSHClient
client = ParallelSSHClient(hosts, user='Administrator', password=''password, pkey='key', port=22, timeout=30)
output = client.run_command(command='ls', user='Administrator', timeout=30)

from pssh.clients.ssh import ParallelSSHClient
client = ParallelSSHClient(hosts, user='Administrator', password=''password, port=22, timeout=30)
output = client.run_command(command='ls', user='Administrator', timeout=30)
or
from pssh.clients.ssh import ParallelSSHClient
client = ParallelSSHClient(hosts, user='Administrator', password=''password, pkey='key', port=22, timeout=30)
output = client.run_command(command='ls', user='Administrator', timeout=30)

# first case:
pssh.exceptions.AuthenticationError: ('Authentication error while connecting to %s:%s - %s', '10.207.225.166', 22, AuthenticationError('Password authentication failed - %s', TypeError('userauth_password() takes exactly 2 positional arguments (1 given)',)))

# second case
sudo : The term 'sudo' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ sudo -u Administrator -S $SHELL -c 'ls'
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (sudo:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Expected behavior**

It should be run ls command on remote windows machine

**Actual behaviour**
What actually happened.

# first case:
pssh.exceptions.AuthenticationError: ('Authentication error while connecting to %s:%s - %s', '10.207.225.166', 22, AuthenticationError('Password authentication failed - %s', TypeError('userauth_password() takes exactly 2 positional arguments (1 given)',)))

# second case
sudo : The term 'sudo' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ sudo -u Administrator -S $SHELL -c 'ls'
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (sudo:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Screenshots**

**Additional information**
Include version of ``ssh2-python`` and any other relevant information.
parallel-ssh (2.5.3)
ssh-python (0.9.0)
ssh2-python (0.26.0)

**Comment by pkittenis** [comment]
Hi there,

Thanks for the interest and report. Password auth not working looks like a bug.

For the second, cannot use `run_command(<..>, user=<..>)` on Windows. `user` uses `sudo`, [per docs](https://parallel-ssh.readthedocs.io/en/latest/ssh_parallel.html#pssh.clients.ssh.parallel.ParallelSSHClient.run_command), which does not exist on windows. Since login user is the same it is not needed.

> user (str) – (Optional) User to run command as. Requires sudo access for that user from the logged in user account.

**Comment by pkittenis** [comment]
Password auth issue resolved in `2.5.4`.
