### ISSUE TITLE
[Feature] IPv6 support

### ISSUE THREAD

**Issue by pkittenis** [ParallelSSH/parallel-ssh#291]
**Is your feature request related to a problem? Please describe.**
It is not possible to use IPv6 addresses, use host names that only resolve to IPv6 addresses, or prefer IPv6 addresses for host names that have both v4 and v6.

**Describe the solution you'd like**
Allow IPv6 addresses to be used by the library. Have a flag to enable/disable IPv6 for host names that resolve to both.

**Describe alternatives you've considered**
Library only supports IPv4.

**Additional context**
N/A

**Comment by sasa-tomic** [comment]
I would love if parallel-ssh had support for IPv6 because we wanted to use it on a network that has *only* IPv6, and it did not work :(
So I'll have to come up with something else to use instead. But parallel-ssh seems to be clearly superior than the alternatives.

**Comment by pkittenis** [comment]
This is the current priority for a new feature.
