### ISSUE TITLE
HostOutput has empty host when authentication fails 

### ISSUE THREAD

**Issue by whuizhe** [ParallelSSH/parallel-ssh#297]
Here's my output
	host=None
	exit_code=None
	channel=None
	exception=('Authentication error while connecting to %s:%s - %s', '10.201.64.106', 22, AuthenticationError('No authentication methods succeeded'))
	encoding=utf-8
	read_timeout=None

When the authentication fails, the host is empty, this time do not know is that ip failure

**Comment by pkittenis** [comment]
Hi there,

Thanks for the interest. Host is available on the exception as the first argument, `host_out.exception.args[0]` as can be seen above.

Should have it as `host_out.host` as well, yes.

**Comment by wfleurant** [comment]
using jumphost / proxy to unreachable target host (host_out.exception):  
`('Proxy authentication failed. Exception from tunnel client: %s', SocketDisconnectError())`

**Comment by pkittenis** [comment]
Resolved by #323
