### ISSUE TITLE
Garbage collection segfault

### ISSUE THREAD

**Issue by maxballenger** [ParallelSSH/parallel-ssh#301]
**Describe the bug**
I am seeing a segfault that seems to be happening in garbage collection. This is inside of large application. It is a test sequencer. The full test sequence takes about 1 hour if it completes and I am seeing this segfault repeatably about 45 minutes into it. I establish two connections with parallel-ssh at the start of the test sequence but I actually don't think I intentionally use them at all during this particular sequence triggering this issue. 

I am using ssh2-python 0.26.0 and parallel-ssh 2.5.4. I also saw the bug with ssh2-python 0.22.0. I don't have a lot here to help debug/reproduce, but if anyone can suggest a possible reason for this that I could work around, that would be very helpful.

```
Thread 144 "python3" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffef7e96700 (LWP 8370)]
0x0000000000000000 in ?? ()
(gdb) wher
#0  0x0000000000000000 in ?? ()
#1  0x00007ffff2bbf91b in _libssh2_channel_free () from /usr/lib/python3.6/site-packages/ssh2/../ssh2_python.libs/libssh2-55f304ca.so.1.0.1
#2  0x00007ffff2bbfa07 in libssh2_channel_free () from /usr/lib/python3.6/site-packages/ssh2/../ssh2_python.libs/libssh2-55f304ca.so.1.0.1
#3  0x00007ffff154386d in __pyx_pf_4ssh2_7channel_7Channel_2__dealloc__ (__pyx_v_self=0x7ffef96c3c88) at ssh2/channel.c:1575
#4  __pyx_pw_4ssh2_7channel_7Channel_3__dealloc__ (__pyx_v_self=<ssh2.channel.Channel at remote 0x7ffef96c3c88>) at ssh2/channel.c:1547
#5  __pyx_tp_dealloc_4ssh2_7channel_Channel (o=<ssh2.channel.Channel at remote 0x7ffef96c3c88>) at ssh2/channel.c:7775
#6  0x0000000000576737 in frame_tp_clear.lto_priv () at ../Objects/frameobject.c:548
#7  0x00000000005a3c0e in delete_garbage (old=<optimized out>, collectable=<optimized out>) at ../Modules/gcmodule.c:864
```

**To Reproduce**

I don't have an easy way to reproduce right now. This is repeatable in my application but it is a large application and it takes about 45 minutes to happen.

**Expected behavior**
No segfault

**Actual behaviour**
segfault

**Screenshots**

**Additional information**
``ssh2-python==0.22.0``
``ssh2-python==0.26.0``
``parallel-ssh==2.5.4``

**Comment by pkittenis** [comment]
Thanks for the interest.

Closing as no steps to reproduce, and seems similar to #304.

If can provide some more information, at least debug log output, can post here.
