### ISSUE TITLE
SCP with sudo

### ISSUE THREAD

**Issue by zwidny** [ParallelSSH/parallel-ssh#305]
I want copy file to remote but I get Permission denied

I expect to add a args like `sudo=True` like below:
```python
from pssh.clients import ParallelSSHClient
from gevent import joinall

client = ParallelSSHClient(hosts)

cmds = client.copy_file('../test', 'test_dir/test', sudo=True)
joinall(cmds, raise_error=True)
```

**Comment by pkittenis** [comment]
Thanks for the interest.

SCP does not support sudo. Sudo is a shell command.

Will need to login with user that has access.
