### ISSUE TITLE
Can not establish ssh connection in multi-processing.

### ISSUE THREAD

**Issue by whbjzzwjxq** [ParallelSSH/parallel-ssh#308]
_For general questions please use the [mail group](https://groups.google.com/forum/#!forum/parallel-ssh)._

**Describe the bug**
Can not use SSHClient in multiProcessing Environment.

**To Reproduce**
Use the following code in functions which are started by pool.starmap.
```python
spec_client = SSHClient(
    host='127.0.0.1', user='xxx', port=9999, pkey='~/.ssh/id_rsa',
    proxy_host='xxx', proxy_user='xxx', proxy_port=9999, proxy_pkey='~/.ssh/id_rsa',
)
def foo():
  host_output = client.run_command(exec_cmd, use_pty=True, read_timeout=15)
      stdouts = []
      try:
          for line in host_output.stdout:
              print(line)
              stdouts.append(line)
      except Timeout:
          pass
    # do Something.
with Pool(4) as pool:
    results = pool.starmap(foo, args)
```
And check both sshd status in localhost and remote, none ssh connection was established.
**Expected behavior**
Print lines to stdout and after more than 15s, nothing happened.

**Actual behavior**
Nothing was printed and Timeout wasn't been raised.

**Screenshots**

**Additional information**
Name: parallel-ssh
Version: 2.5.4
Name: ssh2-python
Version: 0.26.0

**Comment by pkittenis** [comment]
Thanks for the interest.

For doing things in parallel use `ParallelSSHClient`. Trying to mix multiprocessing with the single client is unnecessary, likely not supported by gevent and less efficient if it did work.

See [documentation](https://parallel-ssh.readthedocs.io/en/latest/quickstart.html#run-a-command-on-hosts-in-parallel).
