### ISSUE TITLE
sftp is too slow

### ISSUE THREAD

**Issue by yufengshizhe** [ParallelSSH/parallel-ssh#310]
I found that using sftp to transfer files is very slow
Speed is about 200kb/s
Can you add a quick control parameter

**Comment by pkittenis** [comment]
Thanks for the interest.

To make a bug report please include the following as requested by the bug template.

Steps to reproduce the behavior:
1. Example code that produces error.
2. Stack trace or error messages.

Cannot investigate without the above. The example [sftp copy ](https://github.com/ParallelSSH/parallel-ssh/blob/master/examples/sftp_copy_file.py) transfers in~50MB/s on a localhost. Transfers are dependent on network speed.
