### ISSUE TITLE
Running commands over 1000 hosts

### ISSUE THREAD

**Issue by elchako** [ParallelSSH/parallel-ssh#311]
Good evening! I am trying to execute commands on over 1000 hosts, from a file **ip_test**. But only 1010-1020 is executed.
My py file:

```
with open('ip_test', 'r') as file:
    a = [line.strip() for line in file]
client = ParallelSSHClient(a, user='user', password='12345', num_retries=1, pool_size=300)
cmd = "uname"
output = client.run_command(cmd, stop_on_errors=False)
for host_out in output or []:
    for line in host_out.stdout or []:
        print(line)
```
Thanks for any help!

**Comment by pkittenis** [comment]
Thanks for the interest.

Can you show output, as well as debug logging with `pssh.utils.enable_debug_logger()`.

**Comment by pkittenis** [comment]
Can be re-opened when issue with library is shown.

**Comment by elchako** [comment]
Linux does not allow writing more than 1024 files
I get this error


None [Errno 24] Too many open files
None [Errno 24] Too many open files
None [Errno 24] Too many open files
None [Errno 24] Too many open files
None [Errno 24] Too many open files
None [Errno 24] Too many open files
None [Errno 24] Too many open files

**Comment by pkittenis** [comment]
That is a configuration issue on the system OS. See https://bobcares.com/blog/too-many-open-files/ and `man ulimit`.
