### ISSUE TITLE
save the output of enable_host_logger () to a file

### ISSUE THREAD

**Issue by elchako** [ParallelSSH/parallel-ssh#312]
Good evening! Could you tell me how to save the output of enable_host_logger () to a file
I am using python version

```
from pssh.utils import enable_host_logger
enable_host_logger()
```
Thank you!

**Comment by elchako** [comment]
I apologize, the question is not relevant, I wrote IP in this way
`b.write(f"{host_out.host} \t{line}\n")`

**Comment by pkittenis** [comment]
The logger is a standard python logger. See [python documentation](https://docs.python.org/3/howto/logging.html).
