### ISSUE TITLE
python 3.10 crashes

### ISSUE THREAD

**Issue by wynnw** [ParallelSSH/parallel-ssh#336]
_For general questions please use the [mail group](https://groups.google.com/forum/#!forum/parallel-ssh)._

**Describe the bug**
Using this python 3.10 crashes with:
ImportError: <virtualenv path>/lib/python3.10/site-packages/pssh/native/_ssh2.cpython-310-x86_64-linux-gnu.so: undefined symbol: _PyGen_Send

**To Reproduce**

1. Create a virtualenv with python3.10
2. $ <venv>/bin/pip install parallel-ssh
3. $ <venv/bin/python3.10 -c "from pssh.clients import ParallelSSHClient"

**Expected behavior**
Import should work

**Actual behaviour**
Crash!

**Additional information**
I get parallel-ssh 1.13.0 installed. It looks to be a common problem with the version of cython that was used to generate files and python 3.10. It still crashes if I install cython 0.29.27 into the venv and then run:
 pip install --no-binary "parallel-ssh,ssh2-python" parallel-ssh==1.13.0

See 
https://github.com/cython/cython/issues/3876
for more discussion on the issue.

**Comment by wynnw** [comment]
Looks like this was fixed with ssh2-python here: https://github.com/ParallelSSH/ssh2-python/pull/156

but somehow it hasn't gotten into the parallel-ssh release.

**Comment by wynnw** [comment]
Somehow in reading docs and using pypi.org I ended up installing 1.13.0 and the latest release is 2.8.0 which doesn't have the problem. Not sure how I got in that state. Sorry for the noise.

**Comment by wynnw** [comment]
https://parallel-ssh.readthedocs.io/en/latest/ does work.

**Comment by pkittenis** [comment]
I'll remove the pinned old version of the documentation to avoid confusion. Thanks.
