### ISSUE TITLE
The SSHClient class in ssh/single.py is lacking the copy file functionality that's built into the SSHClient class found in native/single.py 

### ISSUE THREAD

**Issue by sjackson-adaptiv** [ParallelSSH/parallel-ssh#385]
**Is your feature request related to a problem? Please describe.**
I found that in order to authenticate with more recent hosts I had to start using:

`from pssh.clients.ssh import ParallelSSHClient, SSHClient`
rather than
`from pssh.clients import ParallelSSHClient, SSHClient`

This change addressed this issue:
`userauth_pubkey: key type ssh-rsa not in PubkeyAcceptedAlgorithms [preauth]` 

Now that I've made this change, I can once again authenticate with the hosts and interact, with the exception of being able to send/recv files using the sftp or scp functions. It seems that these are missing from ssh/single.py

**Describe the solution you'd like**
It would be great if all the file transfer capabilities described in the [documents](https://parallel-ssh.readthedocs.io/en/latest/advanced.html#sftp-scp) were available in the ssh/single.py 

**Describe alternatives you've considered**
Another possibility is to update the native/single.py  with support for newer ssh authentication methods.

**Additional context**

**Comment by pkittenis** [comment]
That client does not support file copy functionality as of yet due to limitations of the underlying SSH library used. The two clients use different SSH libraries.
