### ISSUE TITLE
Add support for copying remote files to local

### ISSUE THREAD

**Issue by ageekymonk** [ParallelSSH/parallel-ssh#40]
It would be good if we can copy remote files matching a regex to local.

**Comment by pkittenis** [comment]
Certainly possible, though not one for the parallel client (parallel copy from multiple remote hosts to a single local host does not make sense).

What is the use case?

**Comment by ageekymonk** [comment]
My use case is I have lots of servers from where i need to pull logs files for analysis.

**Comment by pkittenis** [comment]
Oh I see. Then parallel copy from multiple hosts to local is indeed the use case. 

It follows that the client would have to de-duplicate files if they conflict, perhaps adding hostname as suffix.
