### ISSUE TITLE
Parse custom ssh_config

### ISSUE THREAD

**Issue by grmpyninja** [ParallelSSH/parallel-ssh#72]
Is there a way to provide a custom ssh_config to parallel-ssh client? A different location than default ones?

I'd like to load it dynamically from different files. I quickly wrote the following to load the file to a dict and then pass it to the `client`

```python
def load_sshconfig(file):
    hosts = dict()
    with open(os.path.expanduser(file)) as f:
        ssh_config = paramiko.SSHConfig()
        ssh_config.parse(f)
        for hostname in ssh_config.get_hostnames():
            if hostname != '*':
                host = ssh_config.lookup(hostname)
                hosts[hostname] = host
        return hosts
        
host_config = load_sshconfig('./ssh_config')
```

as `host_config`, but it doesn't seem to work. I guess formats are different.

**Comment by pkittenis** [comment]
Closing, info provided on how to do this - no code issue has been shown.
