### ISSUE TITLE
Host logger not logging to stdout without output buffer iteration

### ISSUE THREAD

**Issue by pkittenis** [ParallelSSH/parallel-ssh#74]
After `enable_host_logger` is used, logger will only log after output buffer iteration:

```
for line in output[host].stdout:
    pass
<host logger will log>
```

**Comment by Aktariel** [comment]
I'm not sure if this is related, but I'm intermittently getting a message ""No handlers could be found for logger "pssh.ssh_client"" when I attempt to enable host logging. Not sure how to go about debugging or fixing this, though (kind of new to Python). I can share my code if that would be helpful at all.

**Comment by pkittenis** [comment]
It's not relevant nor a bug. See `pssh.utils.enable_host_logger` documentation if you want to make use of it.

**Comment by pkittenis** [comment]
Well having said that, that message can be avoided by having a null handler attached by default. A PR for that would be welcome if you'd like.
