### ISSUE TITLE
parallel_commands.py throws exception=("General SSH error - Error reading SSH protocol banner('This operation would block forever', <Hub at 0x7f05b4026730 epoll pending=0 ref=0 fileno=23>)", 'localhost', 22)

### ISSUE THREAD

**Issue by cy526** [ParallelSSH/parallel-ssh#75]
Running parallel_commands.py throws 
`exception=("General SSH error - Error reading SSH protocol banner('This operation would block forever', <Hub at 0x7f05b4026730 epoll pending=0 ref=0 fileno=23>)", 'localhost', 22)`

**Comment by pkittenis** [comment]
Steps to reproduce?

Works for me on latest version:

```
$ python examples/parallel_commands.py 
Started 10 commands on 1 host(s) in 0:00:00.638215
<...>
All commands finished in 0:00:05.004891
```
