### ISSUE TITLE
Importing paramiko before pssh triggers "This operation would block forever" errors

### ISSUE THREAD

**Issue by ssssam** [ParallelSSH/parallel-ssh#77]
Hello
Thanks for parallel-ssh, I think it's going to be really useful for me!

I hit a problem which seems to be caused by me doing `import paramiko` before doing `import pssh`.

You can reproduce simply by adding `import paramiko` to the top of `examples/parallel_commands.py`, it goes from working as expected to failing with this kind of error:

```
{'localhost': 
	host=localhost
	cmd=<Greenlet at 0x7f0d14041d70>
	channel=None
	stdout=None
	stderr=None
	stdin=None
	exception=("General SSH error - Error reading SSH protocol banner('This operation would block forever', <Hub at 0x7f0d14041e10 epoll pending=0 ref=0 fileno=17>)", 'localhost', 22)
}
```

If `paramiko` is imported after `pssh` then there's no issue.

I can reproduce with Python 2.7 and Python 3.4, commit f64ad595f770e957f1f0b1 of parallel-ssh, and Paramiko 2.1.2. The OS I'm using is CentOS 7.

The reason I added the `import paramiko` line was to load an SSH key following the example here: https://github.com/ParallelSSH/parallel-ssh/blob/master/pssh/pssh_client.py#L262

**Comment by pkittenis** [comment]
Hi there, thanks for the interest.

That is expected. Importing paramiko before pssh stops gevent from patching the standard library before paramiko imports it. Gevent then stops you from trying to use the standard library as if it were asynchronous when it did not patch it to make it asynchronous.

There is a better way to do the above which does not break depending on import order, documentation has been updated.

```
from pssh.utils import load_private_key
client_key = load_private_key('user.key')
client = ParallelSSHClient(['myhost1', 'myhost2'], pkey=client_key)
```

**Comment by ssssam** [comment]
Great, thanks for updating the docs.

I wonder if there's any way to give a better error in this situation -- I lost a few hours trying to work out what was going on, because the 'This operation would block forever' error message mentions nothing about `import` order, and it seems to occur in many different situations (hence searching for the message online doesn't give any indication of what the developer did wrong).

A note in big letters to the README advising users to `import pssh` before anything else would also be helpful.

Thanks again for the library! I managed to write a simple CI system for running compiler builds in about 3 days using Parallel-SSH :-)

**Comment by pkittenis** [comment]
Would also love a better error message, have had to troubleshoot the same thing myself a few times. That would be something to raise on [gevent](https://github.com/gevent/gevent) though, that's where the message is coming from.

Will add a note about import order in the docs.

Glad to hear it's been useful :)
