### ISSUE TITLE
How to use sudo option

### ISSUE THREAD

**Issue by karan1276** [ParallelSSH/parallel-ssh#79]
I want to run command in sudo mode, the bash prompts for password. I am not able to input password using parallel-ssh. What is the correct way to do that.

Sample Code:
```
client.run_command('ls -ltrh /tmp/aasdfasdf', sudo=True)
```

Output:
```
[sudo] password for user:
```
It gets stuck at that. How do i enter my password?

**Comment by pkittenis** [comment]
Should be able to use stdin channel to pass in password:

```
output = client.run_command('ls -ltrh /tmp/aasdfasdf', sudo=True)
host_output = output[client.hosts[0]]
host_output.stdin.writelines([<password>])
host_output.stdin.flush()
<..>
```

Probably best to make sudo password less for the command(s) you want to run though rather than hard code your password into a script. 

Unless an interactive application is being written where user enters password manually instead of course.

**Comment by karan1276** [comment]
> Probably best to make sudo password less for the command(s) you want to run though rather than hard code your password into a script.
Lots of permissions required for that (in a big company) 

Thanks! the code sample you provided works. Maybe it's worth mentioning in the docs? Also `stdin` will be useful for any interaction not only sudo. So some applications are questions while installs, and you have to type `yes`, `stdin` will work there too.

**Comment by pkittenis** [comment]
Glad it works. There is an example of using stdin on [run_command docs](http://parallel-ssh.readthedocs.io/en/latest/pssh_client.html#pssh.pssh_client.ParallelSSHClient.run_command). 

Contributions for more examples always welcome :)
