### ISSUE TITLE
General SSH Error

### ISSUE THREAD

**Issue by doberloh** [ParallelSSH/parallel-ssh#80]
Hey there,

I have searched the web fairly extensively for people having the same issue but I cant seem to find anything that works. I am attempting to connect to an aws instance using pssh but im getting stacktraces. Normal ssh works fine. I am running this with python 3.4.0 on mac 10.11.4:

2017-05-01 11:48:23 pssh.ssh_client ERROR    General SSH error - Error reading SSH protocol banner('This operation would block forever', <Hub at 0x109e96b90 select pending=0 ref=0>)

Any Ideas? If you need more output please let me know.

**Comment by pkittenis** [comment]
Can you please show some code to replicate?

That error is from gevent and it's saying that code is trying to use blocking calls asynchronously, which would never complete - or block the event loop forever (operation would block forever). 

Usually an import order issue. Try removing all non parallel-ssh imports from your code.
