### ISSUE TITLE
Allow proxy host configuration on per-host configuration entries

### ISSUE THREAD

**Issue by pkittenis** [ParallelSSH/parallel-ssh#82]
Currently the per-host configuration provided by `host_config` does not allow for proxy host configuration.

**Comment by BrianMusson** [comment]
+1 would love this

**Comment by pkittenis** [comment]
Blocked by #140 - there can currently only be one proxy per client.

**Comment by pkittenis** [comment]
Host config implementation allows for proxy host to be configured. Still blocked by #140.

**Comment by pkittenis** [comment]
Supported as of `2.2.0`.
