### ISSUE TITLE
Paramiko 2 ?

### ISSUE THREAD

**Issue by marcaurele** [ParallelSSH/parallel-ssh#83]
What's the constraint to keep paramiko < 2 ?

**Comment by pkittenis** [comment]
There are several regressions in paramiko 2, most importantly [this](https://github.com/paramiko/paramiko/issues/980), that make it unusable for parallel-ssh. There are in addition [regressions in performance](https://github.com/paramiko/paramiko/issues/893).

Coincidentally and more FYI at this point, I've been working on a libssh2 based client as an option for future releases which will also avoid the need to monkey patch. Libssh2 has significantly higher performance than paramiko and a solid, tested code base.

Out of interest, what use case do you have for paramiko 2? It will work if you upgrade it manually, parallel-ssh is API compatible with it, but you might run into regressions.

**Comment by marcaurele** [comment]
I had my script written with paramiko 2 originally and wanted to move my ssh tasks to be run in parallel. I saw I could run it with paramiko 2 but I was wondering the reason behind. Thanks for pointing me to those issues. I read many concerns with paramiko.

Good point for the libssh2!

**Comment by pkittenis** [comment]
Yes, I also share concerns about paramiko, hence the work on libssh2 as a replacement :)
