### ISSUE TITLE
Support Kerberos authentication

### ISSUE THREAD

**Issue by ameir** [ParallelSSH/parallel-ssh#85]
Paramiko supports GSS-API authentication, but it looks like parallel-ssh does not leverage that functionality in any way.  It would be great if this could be supported; I have Kerberos-based accounts on jump hosts, and do not have the option to use a password or certificate, so I am out of luck with this library.  I am using this library elsewhere, though, and it is awesome!

**Comment by pkittenis** [comment]
Looks pretty simple to do, it's a couple extra keyword arguments that need to be passed to paramiko for GSS-API authentication to be enabled (`gss_*` arguments to `connect`).

I'll publish a new version that allows for extra arbitrary paramiko arguments to be passed to connect, for this and other arguments not explicitly used by parallel-ssh.

Thanks for the report.

**Comment by ameir** [comment]
That would be awesome.  Thanks a ton!

**Comment by pkittenis** [comment]
[1.1.0 release](https://github.com/ParallelSSH/parallel-ssh/releases/tag/1.1.0) has ability to pass on keyword parameters to paramiko.
