### ISSUE TITLE
error using simple example 

### ISSUE THREAD

**Issue by steelliberty** [ParallelSSH/parallel-ssh#87]
I set the example given in the repository -- 
from pprint import pprint
from pssh.pssh_client import ParallelSSHClient

hosts = [hostname]
client = ParallelSSHClient(hosts,user=username,password=password)

output = client.run_command('ls -ltrh')
pprint (output)

i included the password because I believe it will allow access to my encrypted SSH pkey. 

pssh.exceptions.SSHException: ("General SSH error - Error reading SSH protocol banner('This operation would block forever', <Hub at 0x10ab517d0 select pending=0 ref=0>)", 'nononanananoka.com', 22)

**Comment by pkittenis** [comment]
Hi there,

Thanks for the interest.

Can you please provide a complete code sample that replicates the issue? 

These kind of errors are usually caused by imports of the standard library before pssh, which breaks patching - see note in [quickstart documentation](http://parallel-ssh.readthedocs.io/en/latest/quickstart.html).

Here is what the below code outputs, in latest version:

```
from pprint import pprint
from pssh.pssh_client import ParallelSSHClient

hosts = ['localhost']
client = ParallelSSHClient()

output = client.run_command('ls -ltrh')
pprint (output)

for line in output['localhost'].stdout:
    print line
```

:Output:

```
{'localhost': 
	host=localhost
	exit_code=None
	cmd=<Greenlet at 0x7f971e1b24b0>
	channel=<paramiko.Channel 0 (open) window=2097152 -> <paramiko.Transport at 0x1e1abb50L (cipher aes128-ctr, 128 bits) (active; 1 open channel(s))>>
	stdout=<generator object read_output_buffer at 0x7f971e15c6e0>
	stderr=<generator object read_output_buffer at 0x7f971dee93c0>
	stdin=<paramiko.ChannelFile from <paramiko.Channel 0 (open) window=2097152 -> <paramiko.Transport at 0x1e1abb50L (cipher aes128-ctr, 128 bits) (active; 1 open channel(s))>>>
	exception=None
}

total XXM
rdwx-------- <..>
<..>
```

**Comment by pkittenis** [comment]
Hi @steelliberty - has the problem been resolved? If not, can you please show a code example to replicate and will take a look.

**Comment by steelliberty** [comment]
I have resolved the issue.  It was related to my failure to add location
for my know-hosts file.  Thank you for the follow up.

jack
