### ISSUE TITLE
Error if Host and HostName don't match in ssh_config

### ISSUE THREAD

**Issue by fossil12** [ParallelSSH/parallel-ssh#93]
## Steps to reproduce

1. Add a `Host` entry in your `ssh_config`:

```bash
Host your-server
    HostName 10.0.2.4
```

2. Run the following code:

```python
hosts = ['your-server']
client = ParallelSSHClient(hosts)
client.run_command('ls')
```

## Expected result

The command is executed on "your-server" at `10.0.2.4` like in the first usage example.

## Actual result

A `KeyError: '10.0.2.4'` is raised.

```
Traceback (most recent call last):
  File "./test.py", line 11, in <module>
    output = client.run_command('ls')
  File "pssh/pssh_client.py", line 689, in run_command
    self.get_output(cmd, output, encoding=encoding)
  File "pssh/pssh_client.py", line 778, in get_output
    stdout = self.host_clients[host].read_output_buffer(
KeyError: '10.0.2.4'
```

My research showed that this is due to the fact that `ParallelSSHClient` stores the `SSHClient` at key `your-server`, but the `hostname` returned by `SSHClient` is `10.0.2.4`. 

I'm not so sure how to fix this, thus I'm filing it here.

**Comment by pkittenis** [comment]
Thanks for the report and the reproducible test.
