### ISSUE TITLE
how to pass pem file in  hosts = ['ip']  client = ParallelSSHClient(hosts)

### ISSUE THREAD

**Issue by AbhishekOnedigital** [ParallelSSH/parallel-ssh#94]

**Comment by pkittenis** [comment]
Hi there, thanks for the interest.

Is there an issue being reported here? Will need to show example code, expected output and actual output if so.

**Comment by pkittenis** [comment]
See, [documentation on using private keys](https://parallel-ssh.readthedocs.io/en/latest/advanced.html#programmatic-private-keys) programmatically and via agent. Also [per host](https://parallel-ssh.readthedocs.io/en/latest/advanced.html#per-host-configuration) configuration for the same.

For any issues, please show example code for an issue.
