### ISSUE TITLE
Add scp (non-SFTP) support

### ISSUE THREAD

**Issue by moneill-mw** [ParallelSSH/parallel-ssh#97]
__Current behaviour:__
I am targetting an embedded device (and have limited ability to install software) which is running dropbear (2017.75).  
When I try to use the existing `copy_file` method I get this exception
```Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/paramiko/sftp_client.py", line 103, in __init__
    server_version = self._send_version()
  File "/usr/lib/python3.4/site-packages/paramiko/sftp.py", line 107, in _send_version
    t, data = self._read_packet()
  File "/usr/lib/python3.4/site-packages/paramiko/sftp.py", line 174, in _read_packet
    x = self._read_all(4)
  File "/usr/lib/python3.4/site-packages/paramiko/sftp.py", line 161, in _read_all
    raise EOFError()
```
When I look at the dropbear logs on the device, I see
```
[1204] Nov 06 11:19:43 User usr1 executing '/usr/libexec/sftp-server'
```
but there is no /usr/libexec/sftp-server on the device and I cannot install one.  

I am able to work around this issue by monkey-patching [scp.py](https://github.com/jbardin/scp.py) into the paramiko client.  
```
def fake_copy_scp(self, local_file, remote_file, recurse=False, sftp=None):
    print("fake_copy(%s,%s)"%(local_file, remote_file))
    scpclient = scp.SCPClient(self.client.get_transport())
    scpclient.put(local_file, remote_file)
    scpclient.close()

# Monkey-patch
#pssh.pssh_client.SSHClient.copy_file = fake_copy_scp
```
which then let my copy succeed
```
greenlets = client.copy_file('file.txt', 'file.txt')
joinall(greenlets, raise_error=True)
```
__Desired behaviour:__ 
The existing sftp copy_file functionality is more functional (recursive copy, create remote folder, etc) than the scp.py copy and is definitely to be preferred when the remote servers can support it, but it would be useful to have the (limited/less performant) scp copy behaviour available for use when the remote servers cannot support it without resorting to monkey-patching.  

For my use-case, the addition of a `copy_file_scp(localfile, remotefile)` method would be sufficient.  Support for globbing and/or recursive-copy etc would be nice-to-haves.

Alternatively, some sort of interface which would allow "plugging-in" scp.py operation should also work
```
client = ParallelSSHClient(hosts)
operation = SCPCopier("localfile", "remotefile")
greenlets = client.execute_operation(operation)
```
__Additional info:__ python=3.4.5, OS=CentOS7.4, parallel-ssh=1.2.0, paramiko=2.1.4, ssh2-python=0.6.0
The scp.py module works with the paramiko client, but would need rework/adapting to work with the ssh2 client

**Comment by pkittenis** [comment]
Hi there,

Thanks for the interest and the feature request!

This is something I have been considering adding for the ssh2 client so good to see there are real world use cases for it.

It will only be for the ssh2 client, not paramiko, as paramiko currently [does not support SCP](https://github.com/paramiko/paramiko/issues/150). 

The scp.py module above is a wrapper over a remote `scp` command on the target host and therefore requires the `scp` binary to work. That is opposed to [this project's goals](http://parallel-ssh.readthedocs.io/en/latest/introduction.html#design-and-goals) of providing a library with no external utilities/binaries requirements.

The ssh2 library does have SCP support so this feature is feasible for that client only.

As for monkey patching, can already run `scp` remotely via the existing `run_command` functionality, to do what [scp.py](https://github.com/jbardin/scp.py/blob/master/scp.py#L143-L145) does if that is what you want. There are lots of edge cases that come up with just a cursory glance of that module (non utf-8 filepaths? Windows directory paths?) - in addition to it relying on a binary - that make it unusable for general use cases, though you may decide you are ok with that for your needs.

Sub-classing single or parallel clients to add functionality not already there is another option.

There is no way to allow pluggable operations without them either being specific to the client library or relying on remotely executing a binary, both of which can already be done via the two above methods.

Some documentation on how to extend functionality would be useful though so I think that is worth doing. Please feel free to contribute with your use case if you can.

**Comment by pkittenis** [comment]
`1.6.0` added `scp_recv` and `scp_send` functions to native clients. See [release notes](https://github.com/ParallelSSH/parallel-ssh/releases/tag/1.6.0).
